"""empty message

Revision ID: 2a49ef890f33
Revises: a68c49414ad0
Create Date: 2023-04-04 15:16:10.157616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a49ef890f33'
down_revision = 'a68c49414ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminlog', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])

    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'scenic', ['scenic_id'], ['id'])

    with op.batch_alter_table('oplog', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])

    with op.batch_alter_table('scenic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id'])

    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'scenic', ['scenic_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('face', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_addtime'), ['addtime'], unique=False)
        batch_op.create_unique_constraint(None, ['face'])
        batch_op.create_unique_constraint(None, ['phone'])

    with op.batch_alter_table('userlog', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_addtime'))
        batch_op.drop_column('face')
        batch_op.drop_column('info')
        batch_op.drop_column('phone')

    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('scenic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('oplog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('adminlog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
