"""empty message

Revision ID: 4030ed0be465
Revises: 
Create Date: 2023-04-20 20:53:47.252764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4030ed0be465'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('pwd', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_addtime'), ['addtime'], unique=False)

    op.create_table('emailcaptcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('captcha', sa.String(length=10), nullable=False),
    sa.Column('tag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_addtime'), ['addtime'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=70), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('pwd', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('face', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('face'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_addtime'), ['addtime'], unique=False)

    op.create_table('adminlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adminlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adminlog_addtime'), ['addtime'], unique=False)

    op.create_table('oplog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=600), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oplog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oplog_addtime'), ['addtime'], unique=False)

    op.create_table('scenic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo')
    )
    with op.batch_alter_table('scenic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenic_addtime'), ['addtime'], unique=False)

    op.create_table('userlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userlog_addtime'), ['addtime'], unique=False)

    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collect_addtime'), ['addtime'], unique=False)

    op.create_table('travels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=70), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('scenic_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_travels_addtime'), ['addtime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_travels_addtime'))

    op.drop_table('travels')
    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collect_addtime'))

    op.drop_table('collect')
    with op.batch_alter_table('userlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userlog_addtime'))

    op.drop_table('userlog')
    with op.batch_alter_table('scenic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenic_addtime'))

    op.drop_table('scenic')
    with op.batch_alter_table('oplog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oplog_addtime'))

    op.drop_table('oplog')
    with op.batch_alter_table('adminlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adminlog_addtime'))

    op.drop_table('adminlog')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_addtime'))

    op.drop_table('user')
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_addtime'))

    op.drop_table('suggestion')
    op.drop_table('emailcaptcha')
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_addtime'))

    op.drop_table('area')
    op.drop_table('admin')
    # ### end Alembic commands ###
