"""empty message

Revision ID: bd2deac55877
Revises: 
Create Date: 2023-03-22 19:54:38.193000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd2deac55877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminlog', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=70),
               existing_nullable=True)

    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'scenic', ['scenic_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('oplog', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])

    with op.batch_alter_table('scenic', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('logo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_index('title')
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id'])

    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=70),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'scenic', ['scenic_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=70),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('pwd',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_index('face')
        batch_op.drop_index('ix_user_addtime')
        batch_op.drop_index('phone')
        batch_op.drop_column('info')
        batch_op.drop_column('face')
        batch_op.drop_column('phone')

    with op.batch_alter_table('userlog', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=11), nullable=True))
        batch_op.add_column(sa.Column('face', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('info', mysql.TEXT(), nullable=True))
        batch_op.create_index('phone', ['phone'], unique=False)
        batch_op.create_index('ix_user_addtime', ['addtime'], unique=False)
        batch_op.create_index('face', ['face'], unique=False)
        batch_op.alter_column('pwd',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('travels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('author',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('scenic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('title', ['title'], unique=False)
        batch_op.alter_column('logo',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('oplog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('adminlog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
